jdk:
  - openjdk17
before_install:
  - chmod +x gradlew
install:
  - ./gradlew :lib:assembleRelease
  - ./gradlew :lib:generatePomFileForReleasePublication
jitpack:
  install: ./gradlew :lib:publishToMavenLocal